### ISSUE TITLE
build_reconstruction stalls

### ISSUE THREAD

**Issue by oleg-alexandrov** [sweeneychris/TheiaSfM#8]
Chris,

First, I would like to say that I have been very impressed by TheiaSfM, how the code is clean and implemented using good coding standards, and the care put into documentation. I am having trouble running it though. I made a directory with two images which I have used with other SFM solutions before. Very simple images with lots of features, with a resolution of 640 by 480. I first extracted features:

mkdir -p out_dir; extract_features --input_imgs=img_dir/*.jpg --img_output_dir=./out_dir --num_threads=4 --descriptor=SIFT

That worked. Then I did matching:

match_descriptors --input_imgs=img_dir/*.jpg --img_output_dir=./out_dir --num_threads=4 --descriptor=SIFT --matcher=brute_force --lowes_ratio=0.8

This is where the solver stalled, and even an hour later there is no progress. I attached to it with gdb. Here's where it appears stuck: void ExtractAndMatchFeatures<theia::L2, Eigen::Matrix<float, -1, 1, 0, -1, 1> >(std::vector<theia::Image<float>* ...

I though perhaps you may have some suggestions about what is going on. Thank you!

**Comment by sweeneychris** [comment]
Hi Oleg,

Could you examine the logs with --v=2 enabled? How many images are you
matching? Brute force matching is painfully slow

**Comment by sweeneychris** [comment]
Sorry -- my previous reply was hidden for some reason in Github....

Could you attach the logs with --v=2 enabled? How many images are you
matching? Brute force matching is painfully slow so it may just be taking a long while.

**Comment by oleg-alexandrov** [comment]
Chris, thank you for your reply. I had just two images to match. I figured out the problem finally. Something was messed up with my OpenMP installation. Using --num_threads 1 works, but with more than one thread it stalls. Oddly enough there was no issue in compilation though.

**Comment by sweeneychris** [comment]
Theia does no use openmp... maybe there was something more sinister going
on with the ThreadPool class I have made?! Please let me know if you have
any tips in debugging.

**Comment by oleg-alexandrov** [comment]
I read about OpenMP usage at http://cs.ucsb.edu/~cmsweeney/theia/building.html but that is probably not applicable.

I wiped my entire build and did a clean rebuild on two platforms, SuSE and RedHat. In both cases things are stalling with more than one thread. This is not important to me for the time being, and there's still I chance I messed up something. I may revisit this at a later time.

**Comment by sweeneychris** [comment]
Ok I found the issue. This patch should fix it: https://review.gerrithub.io/#/c/218028/

Please give it a try and let me know if it works for you!

**Comment by oleg-alexandrov** [comment]
Chris, this is great, it works! Thank you!

I have several more very minor issues, specifically errors in compilation, etc. 

First, with gcc 4.9.1 I am getting the following warning, which the compiler treats as error:

TheiaSfM/src/theia/image/keypoint_detector/brisk_impl.cc: In member function ‘float theia::BriskScaleSpace::refine3D(uint8_t, int, int, float&, float&, float&, bool&)’:
TheiaSfM/src/theia/image/keypoint_detector/brisk_impl.cc:603:36: error: ‘delta_x_above’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       x = (r0 * delta_x_layer + r1 * delta_x_above +
                                    ^
I put a simple fix (your code is correct, the compiler is being an ass) at this location: https://github.com/oleg-alexandrov/TheiaSfM/commit/e690a08ac08a7b72b5a25c6c6dc87ec3f6d223b3

Second, the newet version of gflags (2.1.1) moved some things from the google namespace to the gflags namespace. That makes compilation fail as well. Here's an illustration of the fix: https://github.com/oleg-alexandrov/TheiaSfM/commit/92a6c897a31e0ea7be6831e966ca3a5dc4c163c1

I don't see a good fix to make things work with both old and new gflags, save for setting "using namespace google" and "using namespace gflags" then removing the namespace from the function call, letting the compiler choose the right function. 

Third, the link from http://cs.ucsb.edu/~cmsweeney/theia/building.html to the github page seems to point to an old unavailable location. 

Fourth, and here I definitely have nothing better to do with my time, but on the page http://cs.ucsb.edu/~cmsweeney/theia/sfm.html the word "global" is mis-spelled as "gloabl". 

Thank you for your work!

**Comment by sweeneychris** [comment]
Fixed 1, 3, and 4 in the main branch and website. Thanks for reporting!

Regarding 2 -- this is a tricky one. Ceres Solver has some nifty way to handle it... I will look into this for the future. But actually you can choose to build gflags in the gflags namespace still: https://code.google.com/p/gflags/

**Comment by sweeneychris** [comment]
I'm happy to say that with this patch, gflags should work properly regardless of namespace :)

https://review.gerrithub.io/#/c/218170/

Going to close this issue now

**Comment by oleg-alexandrov** [comment]
Sorry to reopen this, but I get an error when cmake is trying to determine whether the namespace of the gflags package is google or gflags. As far as I see it, the problem is the following. The macro CHECK_CXX_SOURCE_COMPILES is invoked. This succeeds in creating a .o file with the right namespace (google or gflags). However, when it comes to link time, and libgflags.a is linked to, it fails, because this library depends on -lpthread. The end result is that cmake says that neither the google nor the gflags namespace works.

**Comment by sweeneychris** [comment]
First, could you try a completely clean build? Something like this:
make clean
rm CMakeCache.txt
cmake ..
make -j4

I just uploaded a patch that should fix linking errors for when you link to the installed Theia library: https://review.gerrithub.io/#/c/218535/

However, your case seems to be during the building on Theia itself? FindGflags.cmake will definitely find all libraries that Gflags needs, so something else must be going on...

**Comment by oleg-alexandrov** [comment]
Chris, thank you for your fixes. The problem is still there though, after wiping the whole build directory and rebuilding. I was not clear enough as to what is going on. The problem shows up when cmake is being run, at the stage where it has to decide whether to use the gflags or google namespace for the gflags package. For me, building both Ceres and Theia fail in exactly the same place, due to the same trick being used. It tries to build an executable and link it to libgflags, but libglags also needs to link to pthread, at least on the RedHat and SuSe systems I tried, so building that executable fails, regardless of whether the google or gflags namespace is used, and not because of that. 

By the way, I have a more serious problem now, theia fails because of missing theia/sfm/filter_view_pairs_from_cycles.h.

**Comment by sweeneychris** [comment]
Can you try to email the Ceres email list about Gflags? I borrowed FindGflags from them, and Alex Stewart is a CMake whiz.

Regarding the missing file: that file should no long exist, and was moved to theia/sfm/filter_view_graph_cycles_by_rotation.h  Can you explain what you mean by "fails"? Likely you will have to run sudo make install again to update the theia/theia.h header for this change.

**Comment by oleg-alexandrov** [comment]
I meant to say the build fails. Here's the offending line:

https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/nonlinear_reconstruction_estimator.cc#L45

**Comment by sweeneychris** [comment]
This should fix it: https://review.gerrithub.io/#/c/218574/

Thanks for letting me know about the bug!

**Comment by oleg-alexandrov** [comment]
Sure. Regarding gflags and ceres, I posted an issue at https://groups.google.com/forum/?hl=en#!topic/ceres-solver/VIBKZCtVR74

**Comment by sweeneychris** [comment]
I saw that the ceres patch was posted. Could you submit the same patch to Theia? Preferably through Gerrit per the website instructions http://cs.ucsb.edu/~cmsweeney/theia/contributions.html

**Comment by sweeneychris** [comment]
Just submitted a patch myself https://review.gerrithub.io/#/c/218642/

**Comment by oleg-alexandrov** [comment]
Chris, sorry, got sidetracked by other stuff. I just verified that the patch you put does the job. Thank you! I am closing this.
